# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

parameters:
  name: ''
  displayName: ''
  body: []
  images: ['ubuntu-18.04', 'macOS-10.15', 'windows-2019']
  versions: ['3.6', '3.7', '3.8']
  packages: ['-e .']

  
jobs:
- job: ${{ parameters.name }}
  variables:
    ${{ if ge(length(parameters.images), 2) }}:
      imgPart: ", {0}"
    ${{ if lt(length(parameters.images), 2) }}:
      imgPart: ""
    ${{ if ge(length(parameters.versions), 2) }}:
      verPart: ", Python {1}"
    ${{ if lt(length(parameters.versions), 2) }}:
      verPart: ""
    ${{ if ge(length(parameters.packages), 2) }}:
      packPart: ", Package {2}"
    ${{ if lt(length(parameters.packages), 2) }}:
      packPart: ""

  strategy:
    matrix:
      ${{ each image in parameters.images }}:
        ${{ each version in parameters.versions }}:
          ${{ each package in parameters.packages }}:
            ${{ format(format('{0}{1}{2}', variables.imgPart, variables.verPart, variables.packPart), image, version, package) }}:
              imageName: ${{ image }}
              python.version: ${{ version }}
              package: ${{ package }}

  pool:
    vmImage: $(imageName)

  displayName: ${{ parameters.displayName }}

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'

  # Enable long path support on Windows so that all packages can be installed correctly
  - script: 'reg add HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f'
    displayName: 'Enable long paths on Windows'
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

  # Install graphviz programmatically on Linux
  - script: 'sudo apt-get -yq install graphviz'
    displayName: 'Install graphviz on Linux'
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  # Install the package
  - script: 'python -m pip install --upgrade pip && pip install --upgrade setuptools wheel Cython && pip install $(package)'
    displayName: 'Install dependencies'

  - ${{ parameters.body }}
