# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'AutoML'
  variables:
    python.version: '3.6'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: azure-pipelines-steps.yml
    parameters:
      body:
        - task: AzureCLI@2
          displayName: 'AutoML tests'
          inputs:
            azureSubscription: 'automl'
            scriptLocation: 'inlineScript'
            scriptType: 'pscore'
            powerShellIgnoreLASTEXITCODE: ''
            inlineScript: |
              $env:SUBSCRIPTION_ID = az account show --query id -o tsv
              python setup.py pytest
          env:
            WORKSPACE_NAME: 'testWorkspace'
            RESOURCE_GROUP: 'testingAutoMLEconML'
            PYTEST_ADDOPTS: '-m "automl"'
            COVERAGE_PROCESS_START: 'setup.cfg'

        - task: PublishTestResults@2
          displayName: 'Publish Test Results **/test-results.xml'
          inputs:
            testResultsFiles: '**/test-results.xml'
            testRunTitle: 'AutoML'
          condition: succeededOrFailed()
