name: Build and Test Notebooks
on:
  push:
    paths:
      - 'notebooks/*'
jobs:
  customer_notebooks:
    runs-on: ubuntu-18.04
    name: Customer Notebooks
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install EconML
        run: pip install -e.[tf,plt]
      # Work around https://github.com/pypa/pip/issues/9542
      - name: Upgrade numpy
        run: pip install -U numpy~=1.21.0
      - name: Install Test Dependencies
        run: install pytest pytest-runner
      - name: Install Jupyter
        run: pip install jupyter jupyter-client
      - name: Install nb
        run: pip install nbconvert nbformat 
      - name: Install misc.   
        run: pip install seaborn xgboost tqdm
      - name: Unit Tests
        run: python setup.py pytest
        env: 
          PYTEST_ADDOPT: '-m "notebook"'
          NOTEBOOK_DIR_PATTERN: 'CustomerScenarios'
        - name: Publish Test Results **/test-results.xml
          uses: EnricoMi/publish-unit-test-result-action@v1
          if: always()
          with:
            files: test-results/**/*.xml